### ISSUE TITLE
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

### ISSUE THREAD

**Issue by andreaferretti** [2vg/MSQueue#4]
I get this error while using MSQueue in a multithreaded settings, for instance in the following example:

```nim
import msqueue, threadpool
var Q = msqInitialize[int]()
var i: int

proc myProc(queue: ptr MsQueue) =
  for ii in 0 .. 1000000:
    queue.push(ii)

spawn myProc(Q)
for ii in 0 .. 1000000:
  discard Q.pop(i)
```

The full stacktrace is

```
Traceback (most recent call last)
threadpool.nim(329)      slave
example.nim(9)           myProcWrapper
example.nim(7)           myProc
msqueue.nim(62)          push
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Traceback (most recent call last)
example.nim(11)          example
msqueue.nim(114)         pop
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

Compile it with `--threads:on`. Unfortunately, the queue only makes sense in a mutlithreaded environment, and this bug makes it quite unusable as is :-(

**Comment by 2vg** [comment]
yes, this is still incomplete.
i brought a concurrent GC from C, so this queue will be rebuilt using that GC.

**Comment by 2vg** [comment]
@andreaferretti and, How about this? [HazardPointer](https://github.com/2vg/hazardPointer)

**Comment by andreaferretti** [comment]
@2vg Thank you, I am not sure how to use hazardPointer, what I actually need is a concurrent queue :-) Do you have any suggestion?

**Comment by 2vg** [comment]
@andreaferretti I recently are investigating concurrent data structures to counter rust 's crossbeam.
So, we first implemented msqueue with Nim's manual memory management, but msqueue seems to get or return memory from a specific free list. (That is not normal malloc etc)
This means that it will not work well with normal memory management.
So, I'm trying to implement msqueue using ref object, but I am suffering because CAS() argument is only bool, int or ptr.
So I made 'concurrent garbage collection'. (To be exact, what I implemented in C was reimplemented with Nim.)
The implementation is in my [nimgc](https://github.com/2vg/nimgc) repository.
Although I think a lot, first of all it may be the best way to find a way to use ref object with CAS().

**Comment by 2vg** [comment]
@andreaferretti Also, the implementation of cues using hazard pointers is in the test directory of the repository.

**Comment by andreaferretti** [comment]
Thank you, I had a brief look at the paper but I could not find how it requires a specific free list. Anyway, thank you for your help! :-)

Please, let me know when MSQueue is going to be working. In the meantime, I am going to do some experiments with hazardPointer

**Comment by 2vg** [comment]
@andreaferretti hi, i remaked MSQueue with ref object.
However, this may not be perfect as well.
If head is not tail, the value should be present.
In this [code](https://github.com/2vg/MSQueue/blob/master/src/msqueue.nim#L78), nil check is done, but it is a process which it does not need...
If you have any other ideas please comment, it is a big welcome !!!!

**Comment by 2vg** [comment]
Probably implementation is okay.
add ATOMIC operation in pop(), nil checking is no longer necessary.
[msqueue.nim#L75](https://github.com/2vg/MSQueue/blob/master/src/msqueue.nim#L75)
[msqueue.nim#L79](https://github.com/2vg/MSQueue/blob/master/src/msqueue.nim#L79)

**Comment by 2vg** [comment]
If you want to see the behavior of the code, you can check it [here](https://wandbox.org/permlink/Ky5z6OyQ0KD9BMuj).

**Comment by 2vg** [comment]
hmm
[https://wandbox.org/permlink/d1gM0SkNnBp4ANy6](https://wandbox.org/permlink/d1gM0SkNnBp4ANy6)

**Comment by andreaferretti** [comment]
I am trying the latest version of MSQueue, but I am getting

```
/Users/andrea/.nimble/pkgs/msqueue-0.4.1/msqueue.nim(40, 15) Error: undeclared identifier: 'atomicStoreN'
```

**Comment by 2vg** [comment]
try `--threads:on`

**Comment by 2vg** [comment]
sad because it is unsafe, but I thought it best using "boehmGC" memory management.
This means that need `--gc: boehm` in all Nim programs that use this queue ...
Alternatively, you can create a Quiescent states based / Epoch based GC and manage memory manually, or can use a hazard pointer.
However, if use hazard pointer, maybe become slow performance because the memory barrier of hazard pointer is strong.
I will continue looking for the best other way to not use "boehmGC"...

**Comment by 2vg** [comment]
implement MPMC MSQueue using epoch based GC.
(For now, no error occurs in my environment)

[https://github.com/2vg/nimgc/blob/master/tests/test2.nim](https://github.com/2vg/nimgc/blob/master/tests/test2.nim)
